# This workflow allows the maintainers to trigger a new release manually
name: Release

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: How major the changes are [ major | minor | patch | beta | exact_semver ]
        required: true
        default: patch

jobs:
  release:
    name: Github and NPM Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.actor }}
          email: ${{ github.actor }}@users.noreply.github.com
      - name: Bump version in package.json and add to CHANGELOG.md
        run: npx standard-version --release-as ${{ github.event.inputs.version-type == 'beta' && 'patch --prerelease beta' || github.event.inputs.version-type }}
      - name: Push Tag to GitHub and Release new NPM version
        run: git push --follow-tags origin master && npm publish ${{ contains(github.event.inputs.version-type, 'beta') && '--tag beta' || '' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
